version: '3.8'

services:
  blockscout-backend:
    image: flashbots/blockscout-backend:${DOCKER_TAG:-latest}-5.3.1
    build: 
      context: https://github.com/adrienmo/blockscout.git#a6792bb5ccfadf71674ecdef5833281fd57a823a
      dockerfile: ./docker/Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        API_V1_READ_METHODS_DISABLED: "false"
        DISABLE_WEBAPP: "false"
        CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED: ""
        ADMIN_PANEL_ENABLED: "false"
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        BLOCKSCOUT_VERSION: "v5.3.1"
        RELEASE_VERSION: "5.3.1"
        CHAIN_TYPE: "suave"
        ERL_FLAGS: "+JPperf true"
      cache_from: type=gha
      cache_to: type=gha,mode=max
    pull_policy: always
    restart: always
    container_name: 'blockscout-backend'
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    env_file:
      -  ../envs/common-blockscout.env
    volumes:
      - ./logs/:/app/logs/
