name: ci

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ['blockscout-stats', 'blockscout-frontend', 'blockscout-backend']
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build images and push to the registry
        run: PATH=/usr/libexec/docker/cli-plugins:${PATH} make explorer-build-and-push
        env:
          APP: ${{ matrix.app }}
          DOCKER_TAG: ${{ github.ref }}